spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/orcl
#    username: sales
#    password: sales
#    driver-class-name: oracle.jdbc.driver.OracleDriver
  datasource:
    url: jdbc:mysql://localhost:3306/Erp
    username: root
    password: smartcode
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  hibernate:
    ddl-auto: update
#logging:
#  level:
#    root: DEBUG
#    org.springframework: DEBUG
#    org.hibernate: DEBUG
server:
  port: 9090